# Generated by Django 4.2.10 on 2024-03-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='year',
        ),
    ]
